// data/products.js

export const ProductsData = [
    {
      id: 1,
      image: "/image 1.png",
      title: "T-SHIRT WITH TAPE DETAILS",
      category: "Casual",
      price: "$120",
      priceWas: "",
      discountPercentage: 0,
      rating: 4.6,
      description: "Comfortable t-shirt with unique tape details.",
      color: "Gray",
      quantity:10,
      aosDelay: 800,
    },
    {
      id: 2,
      image: "/newarr2.png",
      title: "SKINNY FIT JEANS",
      category: "Casual",
      price: "$240",
      priceWas: "$260",
      discountPercentage: 10,
      rating: 4.8,
      description: "Stylish skinny fit jeans for all occasions.",
      quantity:10,
    },
    {
      id: 3,
      image: "/newarr3.png",
      title: "CHECKERED SHIRT",
      category: "Casual",
      price: "$180",
      priceWas: "",
      discountPercentage: 0,
      rating: 4.8,
      description: "Classic checkered shirt for casual wear.",
      quantity:10,
    },
    {
      id: 4,
      image: "/newarr4.png",
      title: "SLEEVE STRIPED T-SHIRT",
      category: "Gym",
      price: "$130",
      priceWas: "$160",
      discountPercentage: 10,
      rating: 4.7,
      description: "Striped t-shirt for a modern look.",
      quantity:10,
      color: "Gray",
      aosDelay: 800,
    },
    {
      id: 5,
      image: "/topsell1.png",
      title: "VERTICAL STRIPED SHIRT",
      price: "$212",
      category: "Formal",
      priceWas: "$232",
      rating: 4.7,
      discountPercentage: 10,
      description: "Trendy vertical striped shirt for all seasons.",
      quantity:10,
      color: "Gray",
      aosDelay: 800,
    },
    {
      id: 6,
      image: "/topsell2.png",
      title: "COURAGE GRAPHIC T-SHIRT",
      category: "Casual",
      price: "$145",
      priceWas: "",
      rating: 4.0,
      discountPercentage: 0,
      description: "Bold graphic t-shirt with motivational quotes.",
      quantity:10,
      color: "Gray",
      aosDelay: 800,
    },
    {
      id: 7,
      category: "Party",
      image: "/images/accessories/leather-belt2.jpg",
      title: "Women's Luxury Watch",
      price: "$119.99",
      priceWas: "",
      rating: 4.8,
      discountPercentage: 0,
      description: "Elegant and chic luxury watch for women.",
      quantity:10,
      color: "Gray",
      aosDelay: 800,
      
    },
    {
      id: 8,
      category: "Casual",
      image: "/images/men-clothing/t-shirts-2 (4).png",
      title: "Casual T-Shirt",
      price: "$12.99",
      priceWas: "$14.99",
      rating: 4.7,
      discountPercentage: 10,
      description: "Everyday casual t-shirt for relaxed style.", 
      quantity:10,    
      color: "Gray",
      aosDelay: 800,
    },
    {
      id: 9,
      title: "Formal Shirt",
      description: "Perfectly tailored formal shirt for office wear.",
      image: "/images/men-clothing/full-sleeve-shirt.png",
      category: "Casual",
      rating: 4.4,
      price: "$34.99",
      priceWas: "",
      discountPercentage: 0,
      color: "White",
      aosDelay: 900,
    },
    {
      id: 10,
      title: "Classic Denim Short",
      description: "Timeless denim shorts for all seasons.",
      quantity:10,
      image: "/images/men-clothing/denim-bottom (3).png",
      category: "Casual",
      rating: 4.3,
      price: "$59.99",
      priceWas: "$79.99",
      discountPercentage: 20,
      color: "Blue",
      aosDelay: 1000,
    },
    {
        id: 11,
        title: "Sports Watch",
        description: "Durable sports watch for outdoor enthusiasts.",
        quantity:10,
        image: "/images/accessories/wallet.jpg",
        category: "Gym",
        rating: 4.9,
        price: "$89.99",
        priceWas: "$109.99",
        discountPercentage: 30,
        color: "Silver",
        aosDelay: 1100,
      },
      {
        id: 12,
        title: "Fashion Bracelet",
        description: "Beautiful bracelet to complement any outfit.",
        image: "/images/accessories/bracelet2.jpg",
        category: "Accessories",
        rating: 4.9,
        price: "$24.99",
        priceWas: "",
        discountPercentage: 0,
        color: "Gold",
        quantity:10,
        aosDelay: 1200,
      },
      {
        id: 13,
        title: "Leather Belt",
        description: "High-quality leather belt for a sophisticated look.",
        image: "/images/accessories/leather-belt1.jpg",
        category: "Accessories",
        rating: 4.6,
        price: "$29.99",
        priceWas: "$39.99",
        discountPercentage: 10,
        color: "Brown",
        quantity:10,
        aosDelay: 1300,
      },
      {
        id: 14,
        title: "Polarized Sunglasses",
        description: "Protect your eyes with stylish polarized sunglasses.",
        image: "/images/accessories/sunglasses.jpg",
        category: "Accessories",
        rating: 4.8,
        price: "$49.99",
        priceWas: "",
        discountPercentage: 0,
        color: "Black",
        quantity:10,
        aosDelay: 1400,
      },
      {
        id: 15,
        title: "Summer Dress",
        description: "Light and airy summer dress for warm days.",
        image: "/images/men-clothing/t-shirts-1 (3).png",
        category: "Casual",
        rating: 4.7,
        price: "$34.99",
        priceWas: "$39.99",
        discountPercentage: 10,
        quantity:10,
        color: "Yellow",
        aosDelay: 1500,
      },
      {
        id: 16,
        title: "Sneakers",
        description: "Comfortable sneakers for everyday use.",
        image: "/images/shoes/running-1.jpg",
        category: "Casual",
        rating: 4.9,
        price: "$59.99",
        priceWas: "$80.00",
        discountPercentage: 20,
        color: "White",
        quantity:10,
        aosDelay: 1600,
      },
      {
        id: 17,
        title: "Running Shoes",
        description: "Lightweight running shoes for active lifestyles.",
        image: "/images/shoes/running2.jpg",
        category: "Footwear",
        rating: 4.8,
        price: "$69.99",
        priceWas: "$79.99",
        discountPercentage: 10,
        color: "Blue",
        quantity:10,
        aosDelay: 1700,
      },
      {
        id: 18,
        title: "Classic Wallet",
        description: "Minimalistic wallet made of genuine leather.",
        image: "/images/accessories/wallet2.jpg",
        category: "Accessories",
        rating: 4.6,
        price: "$19.99",
        priceWas: "",
        discountPercentage: 0,
        color: "Brown",
        quantity:10,
        aosDelay: 1800,
      },
      {
        id: 19,
        title: "Hoodie",
        description: "Cozy hoodie for chilly days.",
        image: "/images/hoodie/hoodie1.jpg",
        category: "Casual",
        rating: 4.7,
        price: "$39.99",
        priceWas: "",
        discountPercentage: 0,
        color: "Gray",
        quantity:10,
        aosDelay: 1900,
      },
      {
        id: 20,
        title: "Formal Shoes",
        description: "Elegant formal shoes for office wear.",
        image: "/images/shoes/formal-shoe.jpg",
        category: "Footwear",
        rating: 4.9,
        price: "$89.99",
        priceWas: "$99.99",
        discountPercentage: 10,
        color: "Black",
        quantity:10,
        aosDelay: 2000,
      },
      {
        id: 21,
        image: "/maylike2.png",
        category: "Formal",
        description: "Elegant for office wear.",
        title: "Polo with Contrast Trims",
        price: "$212",
        priceWas: "$242",
        discountPercentage: 20,
        quantity:10,
        rating: 4.0,
      },
      {
        id: 22,
        image: "/maylike3.png",
        category: "Formal",
        description: "Elegant for office wear.",
        title: "Gradient Graphic T-shirt",
        price: "$145",
        priceWas: "",
        discountPercentage: 0,
        rating: 3.5,
        quantity:10,
      },
      {
          id: 23,
          image: "/maylike1.png",
          title: "Polo with Tipping Details",
          category: "Formal",
          description: "Elegant for office wear.",
          price: "$180",
          priceWas: "",
          discountPercentage: 0,
          rating: 4.5,
          quantity:10,
        },
      {
        id: 24,
        image: "/maylike4.png",
        title: "Black Striped T-shirt",
        category: "Formal",
        description: "Elegant for office wear.",
        price: "$120",
        priceWas: "$160",
        discountPercentage: 35,
        rating: 5.0,
        quantity:10,
      },
    // Add other products here...
  ];
   // Categorizing data

  
// New Arrivals
export const NewArrivals = ProductsData.filter(product => !product.priceWas);

// Top Selling (criteria: rating > 4.7)
export const TopSell = ProductsData.filter(product => product.rating > 4.7);

// Products You May Like (criteria: rating > 4.5 && priceWas is not empty)
export const ProductsYouMayLike = ProductsData.filter(
  product => product.rating > 4.5 && product.priceWas
);

// Products Formals
export const Formals = ProductsData.filter(product => product.category.toLowerCase() === "formal");
console.log(Formals)

//Casual Products
export const Casuals = ProductsData.filter(product => product.category.toLowerCase() === "casual");

//Gym Products
export const Gym = ProductsData.filter(product => product.category.toLowerCase() === "gym");

// Accessories
export const accessories = ProductsData.filter(product => product.category.toLowerCase() === "accessories");

// Party Products
export const Party = ProductsData.filter(product => product.category.toLowerCase() === "party");

// Footwear

export const Footwear = ProductsData.filter(product => product.category.toLowerCase() === "footwear");